### ISSUE TITLE
Error while trying to run the bot

### ISSUE THREAD

**Issue by M-Mahou** [dmarx/discord-comfybot#1]
I get this error when i try to run the bot

Cmd runned : discord-bot

```
Traceback (most recent call last):
  File "/notebooks/bot/discord-comfybot/.venv/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/notebooks/bot/discord-comfybot/.venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/notebooks/bot/discord-comfybot/.venv/lib/python3.10/site-packages/discord_bot/bot.py", line 91, in on_ready
    bot.workflow_mgr = WorkflowManager()
  File "/notebooks/bot/discord-comfybot/.venv/lib/python3.10/site-packages/comfy_utils/workflow_manager.py", line 115, in __init__
    self.set_active(active_workflow_name)
  File "/notebooks/bot/discord-comfybot/.venv/lib/python3.10/site-packages/comfy_utils/workflow_manager.py", line 151, in set_active
    self.refresh_workflow_registry()
  File "/notebooks/bot/discord-comfybot/.venv/lib/python3.10/site-packages/comfy_utils/workflow_manager.py", line 123, in refresh_workflow_registry
    self.workflow_registry = {wf_name:Workflow(name=wf_name) for wf_name in list_saved_workflows(api_only=True)}
  File "/notebooks/bot/discord-comfybot/.venv/lib/python3.10/site-packages/comfy_utils/comfy_client.py", line 56, in list_saved_workflows
    outv = response.json()
  File "/notebooks/bot/discord-comfybot/.venv/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3)
```

on debian

![image](https://github.com/dmarx/discord-comfybot/assets/95573111/62962e82-a7a4-4e0e-9d79-2999554770b0)

**Comment by dmarx** [comment]
is comfy running? if so, what extensions do you have installed? do you have comfy manager installed?

**Comment by sten-henriksson** [comment]
I get the same running comfyui outof the box with 1 checkpoint downloaded

**Comment by dmarx** [comment]
sorry, i need to update the setup instructions. the latest version of the bot assumes you have the comfyui manager and comfyui custom scripts extensions installed. Run the following to install them and see if that gets it working.

```
cd ComfyUI/custom_nodes
git clone https://github.com/ltdrdata/ComfyUI-Manager
git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts
```
